src/Entity/ChargeNFX.php
<?php

namespace App\Entity;

use App\Repository\ChargeNFXRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChargeNFXRepository::class)
 */
class ChargeNFX
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $poids_charge;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prise_hauteur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prise_profondeur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $depose_hauteur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $depose_profondeur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_initiale;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_initiale_reference;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_maintien;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_maintien_reference;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $distance_transport_charge;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $transport_charge;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_action;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_manutention_type;

    private $PT_lit;

    private $PT_transpalette;

    private $PT_chariot;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PT_distance;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PT_hauteur_poignee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_frequence;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_charge_identique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contraintes_execution;

    private $contrainte_poignees_inadaptees;

    private $contrainte_torsion_tronc;

    private $contrainte_profondeur_prise;

    private $contrainte_hors_zone_atteinte;

    private $contrainte_posture;

    private $contrainte_charge_instable;

    private $contrainte_visibilite_limitee;

    private $contrainte_roulettes_inadequates;

    private $contrainte_absence_frein;

    /**
     * @ORM\ManyToOne(targetEntity=EvaluationNFX::class, inversedBy="chargeNFXes")
     */
    private $evaluation_nfx;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coefficient_correction_1;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coefficient_correction_2;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $masse_corrigee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $intitule_coefficient_correction_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $intitule_coefficient_correction_2;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoidsCharge(): ?float
    {
        return $this->poids_charge;
    }

    public function setPoidsCharge(float $poids_charge): self
    {
        $this->poids_charge = $poids_charge;

        return $this;
    }

    public function getPriseHauteur(): ?float
    {
        return $this->prise_hauteur;
    }

    public function setPriseHauteur(float $prise_hauteur): self
    {
        $this->prise_hauteur = $prise_hauteur;

        return $this;
    }

    public function getPriseProfondeur(): ?float
    {
        return $this->prise_profondeur;
    }

    public function setPriseProfondeur(float $prise_profondeur): self
    {
        $this->prise_profondeur = $prise_profondeur;

        return $this;
    }

    public function getDeposeHauteur(): ?float
    {
        return $this->depose_hauteur;
    }

    public function setDeposeHauteur(float $depose_hauteur): self
    {
        $this->depose_hauteur = $depose_hauteur;

        return $this;
    }

    public function getDeposeProfondeur(): ?float
    {
        return $this->depose_profondeur;
    }

    public function setDeposeProfondeur(float $depose_profondeur): self
    {
        $this->depose_profondeur = $depose_profondeur;

        return $this;
    }

    public function getForceInitiale(): ?float
    {
        return $this->force_initiale;
    }

    public function setForceInitiale(float $force_initiale): self
    {
        $this->force_initiale = $force_initiale;

        return $this;
    }

    public function getForceInitialeReference(): ?float
    {
        return $this->force_initiale_reference;
    }

    public function setForceInitialeReference(float $force_initiale_reference): self
    {
        $this->force_initiale_reference = $force_initiale_reference;

        return $this;
    }

    public function getForceMaintien(): ?float
    {
        return $this->force_maintien;
    }

    public function setForceMaintien(?float $force_maintien): self
    {
        $this->force_maintien = $force_maintien;

        return $this;
    }

    public function getForceMaintienReference(): ?float
    {
        return $this->force_maintien_reference;
    }

    public function setForceMaintienReference(?float $force_maintien_reference): self
    {
        $this->force_maintien_reference = $force_maintien_reference;

        return $this;
    }

    public function getDistanceTransportCharge(): ?float
    {
        return $this->distance_transport_charge;
    }

    public function setDistanceTransportCharge(float $distance_transport_charge): self
    {
        $this->distance_transport_charge = $distance_transport_charge;

        return $this;
    }

    public function getTransportCharge(): ?string
    {
        return $this->transport_charge;
    }

    public function setTransportCharge(string $transport_charge): self
    {
        $this->transport_charge = $transport_charge;

        return $this;
    }

    public function getPTAction(): ?string
    {
        return $this->PT_action;
    }

    public function setPTAction(?string $PT_action): self
    {
        $this->PT_action = $PT_action;

        return $this;
    }

    public function getPTManutentionType(): ?string
    {
        return $this->PT_manutention_type;
    }

    public function setPTManutentionType(?string $PT_manutention_type): self
    {
        $this->PT_manutention_type = $PT_manutention_type;

        return $this;
    }

    public function getPTLit(): ?bool
    {
        return $this->PT_lit;
    }

    public function setPTLit(bool $PT_lit): self
    {
        $this->PT_lit = $PT_lit;

        return $this;
    }

    public function getPTTranspalette(): ?bool
    {
        return $this->PT_transpalette;
    }

    public function setPTTranspalette(bool $PT_transpalette): self
    {
        $this->PT_transpalette = $PT_transpalette;

        return $this;
    }

    public function getPTchariot(): ?bool
    {
        return $this->PT_chariot;
    }

    public function setPTchariot(bool $PT_chariot): self
    {
        $this->PT_chariot = $PT_chariot;

        return $this;
    }

    public function getPTDistance(): ?float
    {
        return $this->PT_distance;
    }

    public function setPTDistance(?float $PT_distance): self
    {
        $this->PT_distance = $PT_distance;

        return $this;
    }

    public function getPTHauteurPoignee(): ?float
    {
        return $this->PT_hauteur_poignee;
    }

    public function setPTHauteurPoignee(?float $PT_hauteur_poignee): self
    {
        $this->PT_hauteur_poignee = $PT_hauteur_poignee;

        return $this;
    }

    public function getPTFrequence(): ?string
    {
        return $this->PT_frequence;
    }

    public function setPTFrequence(?string $PT_frequence): self
    {
        $this->PT_frequence = $PT_frequence;

        return $this;
    }

    public function getNombreChargeIdentique(): ?int
    {
        return $this->nombre_charge_identique;
    }

    public function setNombreChargeIdentique(int $nombre_charge_identique): self
    {
        $this->nombre_charge_identique = $nombre_charge_identique;

        return $this;
    }

    public function getContraintesExecution(): ?string
    {
        return $this->contraintes_execution;
    }

    public function setContraintesExecution(string $contraintes_execution): self
    {
        $this->contraintes_execution = $contraintes_execution;

        return $this;
    }

    public function getEvaluationNfx(): ?EvaluationNFX
    {
        return $this->evaluation_nfx;
    }

    public function setEvaluationNfx(?EvaluationNFX $evaluation_nfx): self
    {
        $this->evaluation_nfx = $evaluation_nfx;

        return $this;
    }

    public function getContraintePoigneesInadaptees(): ?bool
    {
        return $this->contrainte_poignees_inadaptees;
    }

    public function setContraintePoigneesInadaptees(bool $contrainte_poignees_inadaptees): self
    {
        $this->contrainte_poignees_inadaptees = $contrainte_poignees_inadaptees;

        return $this;
    }

    public function getContrainteTorsionTronc(): ?bool
    {
        return $this->contrainte_torsion_tronc;
    }

    public function setContrainteTorsionTronc(bool $contrainte_torsion_tronc): self
    {
        $this->contrainte_torsion_tronc = $contrainte_torsion_tronc;

        return $this;
    }

    public function getContrainteProfondeurPrise(): ?bool
    {
        return $this->contrainte_profondeur_prise;
    }

    public function setContrainteProfondeurPrise(bool $contrainte_profondeur_prise): self
    {
        $this->contrainte_profondeur_prise = $contrainte_profondeur_prise;

        return $this;
    }

src/Entity/Fichier.php
<?php

namespace App\Entity;

use App\Repository\FichierRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FichierRepository::class)
 */
class Fichier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_fichier;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_fichier;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_fichier;

    /**
     * @ORM\ManyToOne(targetEntity=Situation::class)
     */
    private $situation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFichier()
    {
        return $this->nom_fichier;
    }

    public function setNomFichier($nom_fichier)
    {
        $this->nom_fichier = $nom_fichier;

        return $this;
    }

    public function getTypeFichier(): ?string
    {
        return $this->type_fichier;
    }

    public function setTypeFichier(string $type_fichier): self
    {
        $this->type_fichier = $type_fichier;

        return $this;
    }

    public function getDateFichier(): ?String
    {
        return $this->date_fichier;
    }

    public function setDateFichier(?string $date_fichier): self
    {
        $this->date_fichier = $date_fichier;

        return $this;
    }

    public function getSituation(): ?Situation
    {
        return $this->situation;
    }

    public function setSituation(?Situation $situation): self
    {
        $this->situation = $situation;

        return $this;
    }
}

templates/NFX35109/activity.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <div class="row">
            <h1>{% trans %}Repérer{% endtrans %}</h1>
            <h1>></h1>
            <h1>{% trans %}Hiérarchiser{% endtrans %}</h1>
            <h1>></h1>
            <h1 class="mauve">{% trans %}Évaluer{% endtrans %}</h1>
        </div>

        {{ form_start(form) }}

        <div>
            <h1>{% trans %}Manutention Manuelle de charge - Situation{% endtrans %}</h1>
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                        <p class="text_margin_right">{% trans %}Nom Évaluateur :{% endtrans %}</p>
                        <p>{{ evaluateur.prenom }} {{ evaluateur.nom }}</p>

                        <p class="text_margin_right">{% trans %}Entreprise :{% endtrans %}</p>
                        {{ form_widget(form.entreprise.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Ex: Amazon...'}} ) }}
                        
                        <p class="text_margin_right">{% trans %}Site :{% endtrans %}</p>
                        {{ form_widget(form.site.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Ex: Amiens...'}} ) }}
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 hr_left2">
                        <p class="text_margin_right">{% trans %}Nom du secteur :{% endtrans %}</p>
                        {{ form_widget(form.secteur.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Ex: Production...'}} ) }}
                        
                        <p class="text_margin_right">{% trans %}Poste de travail :{% endtrans %}</p>
                        {{ form_widget(form.posteDeTravail.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Ex: Fin de chaîne...'}} ) }}
                        
                        <p class="text_margin_right">{% trans %}Nom de la situation :{% endtrans %}</p>
                        {{ form_widget(form.situation_nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Ex: Dépalettisation...'}} ) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_tool_NFX35109',  { 'id': evaluateur.id }) }}">{% trans %}Annuler{% endtrans %}</a>
            {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/NFX35109/execution.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div>
        <div>
            <h1>Conditions d'exécution</h1>
            <div class="group_button">
                <p>Poids de la charge (en kg) :</p>
                <div class="number">
                    <span class="minus">-</span>
                    <input type="text" class="input_number" value="1"/>
                    <span class="plus">+</span>
                </div>
            </div>
            <p>Prise de la charge :</p>
            <p>Hauteur (m)</p>
            <p>Profondeur (m)</p>
            <p>Dépôt de la charge :</p>
            <p>Hauteur (m)</p>
            <p>Profondeur (m)</p>
            <p>Effort pousser/tirer :</p>
            <p>Force initiale (daN)</p>
            <p>Force de maintien (daN)</p>
            <p>Distance de transport de la charge (m) :</p>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_tool_NFX35109') }}" >Revoir les conditions</a>
            <a class="button3_right" href="{{ path('adept_NFX35109_references_conditions') }}" >Continuer</a>
        </div>
    </div>
{% endblock %}

templates/NFX35109/handlingWithAssistanceResume.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <div>
            <div class="row">
                <h1>{% trans %}Repérer{% endtrans %}</h1>
                <h1>></h1>
                <h1>{% trans %}Hiérarchiser{% endtrans %}</h1>
                <h1>></h1>
                <h1 class="mauve">{% trans %}Évaluer{% endtrans %}</h1>
            </div>
            <h1>{% trans %}Manutention Manuelle de charge - Bilan de la Manutention Manuelle avec aide à la manutention{% endtrans %}</h1>
            <hr>
            <div class="row constraints">
                <h4>{% trans %}Bilan :{% endtrans %}</h4>
                <h4 class="icon_green">+</h4>
                <h4>{% trans %}Conditions favorables{% endtrans %}</h4>
                <h4 class="icon_yellow">-</h4>
                <h4>{% trans %}Les points à améliorer{% endtrans %}</h4>
                <h4 class="icon_red">-</h4>
                <h4>{% trans %}Les facteurs les plus pénalisants{% endtrans %}</h4>
            </div>
            <table class="table table-striped table-hover table-light">
                <thead>
                    <tr>
                        <th scope="col">N°</th>
                        <th scope="col">{% trans %}Type manutention{% endtrans %}</th>
                        <th scope="col">{% trans %}Masse (kg){% endtrans %}</th>
                        <th scope="col">{% trans %}Force initiale (en daN){% endtrans %}</th>
                        <th scope="col">{% trans %}Force de maintien(en daN){% endtrans %}</th>
                        <th scope="col">{% trans %}Fréquence{% endtrans %}</th>
                        <th scope="col">{% trans %}Détails{% endtrans %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for charge in charges %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>
                            {{ charge.PTManutentionType | capitalize  }}
                        </td>
                        <td>
                            {{ charge.poidsCharge }}
                        </td>
                        {% if charge.forceInitiale >= charge.forceInitialeReference %}
                            <td class="resume_green">
                                {{ charge.forceInitiale }}
                            </td>
                        {% else %}
                            <td class="resume_red">
                                {{ charge.forceInitiale }}
                            </td>
                        {% endif %}
                        {% if charge.forceMaintien >= charge.forceMaintienReference %}
                            <td class="resume_green">
                                {{ charge.forceMaintien }}
                            </td>
                        {% else %}
                            <td class="resume_red">
                                {{ charge.forceMaintien }}
                            </td>
                        {% endif %}
                        <td>
                            {{ charge.PTFrequence }}
                        </td>
                        <td scope="col">
                            <a href="{{ path('adept_NFX35109_handling_with_assistance_resume_charge',  { 'id': idEvaluation, 'id2': charge.id }) }}">
                                <img src="/images/icon_loupe.png" class="icon_click" alt="icon loupe" id="icon_loupe_1">
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {{ form_start(form) }}
        <div class="modal fade" id="ModalCenterTerminer" tabindex="-1" role="dialog" aria-labelledby="Enregistrer l'analyse" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header card_header_animation">
                        <h5 class="modal-title">{% trans %}Enregistrer l'analyse{% endtrans %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div>
                        <div class="row_flex modal_margin modal_label">
                            <p class="text_margin_right p_black">{% trans %}Nom :{% endtrans %}</p>
                            {{ form_widget(form.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Nom...'}} ) }}
                        </div>
                    </div>
                    <div class="group_button modal_margin">
                        <button type="button" class="button3_left" data-dismiss="modal">{% trans %}Annuler{% endtrans %}</button>
                        {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}

        <div class="group_button">
            <a class="button4_left" href="{{ path('adept_NFX35109_handling_with_assistance_constraints',  { 'id': idEvaluation }) }}">{% trans %}Revenir en arrière{% endtrans %}</a>
            <a class="button4_center" href="{{ path('adept_NFX35109_handling_with_assistance',  { 'id': idEvaluation }) }}">{% trans %}Ajouter une charge{% endtrans %}</a>
            <button id="button_Terminer" type="button" class="button4_center" data-toggle="modal" data-target="#ModalCenterTerminer">{% trans %}Terminer{% endtrans %}</button>
            {% if evaluation.evaluationEd6161 != null %}
                <a class="button4_right" href="{{ path('adept_ED6161_resume', { 'id': evaluation.evaluationEd6161.evaluation.id }) }}">{% trans %}Retour à la hiérarchisation{% endtrans %}</a>
            {% else %}
                <a class="button4_right" href="{{ path('adept_menu') }}">{% trans %}Retour au menu principal{% endtrans %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/NFX35109/handlingWithoutAssistanceResume.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <div>
            <div class="row">
                <h1>{% trans %}Repérer{% endtrans %}</h1>
                <h1>></h1>
                <h1>{% trans %}Hiérarchiser{% endtrans %}</h1>
                <h1>></h1>
                <h1 class="mauve">{% trans %}Évaluer{% endtrans %}</h1>
            </div>
            <h1>{% trans %}Manutention Manuelle de charge - Bilan de la Manutention Manuelle sans aide à la manutention{% endtrans %}</h1>
            <hr>
            <div class="row constraints">
                <h4>{% trans %}Bilan :{% endtrans %}</h4>
                <h4 class="icon_green">+</h4>
                <h4>{% trans %}Conditions favorables{% endtrans %}</h4>
                <h4 class="icon_yellow">-</h4>
                <h4>{% trans %}Les points à améliorer{% endtrans %}</h4>
                <h4 class="icon_red">-</h4>
                <h4>{% trans %}Les facteurs les plus pénalisants{% endtrans %}</h4>
            </div>
            <table class="table table-striped table-hover table-light">
                <thead>
                    <tr>
                        <th scope="col">N°</th>
                        <th scope="col">{% trans %}Masse (kg){% endtrans %}</th>
                        <th scope="col">{% trans %}Coefficient 1{% endtrans %}</th>
                        <th scope="col">{% trans %}Coefficient 2{% endtrans %}</th>
                        <th scope="col">{% trans %}Masse corrigée (en kg){% endtrans %}</th>
                        <th scope="col">{% trans %}Détails{% endtrans %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for charge in charges %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>
                            {{ charge.poidsCharge }}
                        </td>
                        {% if charge.coefficientCorrection1 == 1 %}
                            <td class="resume_green">
                                {{ charge.coefficientCorrection1 }}
                            </td>
                        {% else %}
                            <td class="resume_red">
                                {{ charge.intituleCoefficientCorrection1 }} :
                                {{ charge.coefficientCorrection1 }}
                            </td>
                        {% endif %}
                        {% if charge.coefficientCorrection2 == 1 %}
                            <td class="resume_green">
                                {{ charge.coefficientCorrection2 }}
                            </td>
                        {% else %}
                            <td class="resume_red">
                                {{ charge.intituleCoefficientCorrection2 }} :
                                {{ charge.coefficientCorrection2 }}
                            </td>
                        {% endif %}
                        <td>
                            {{ charge.masseCorrigee }}
                        </td>
                        <td scope="col">
                            <a href="{{ path('adept_NFX35109_handling_without_assistance_resume_charge',  { 'id': idEvaluation, 'id2': charge.id }) }}">
                                <img src="/images/icon_loupe.png" class="icon_click" alt="icon loupe" id="icon_loupe_1">
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {{ form_start(form) }}
        <div class="modal fade" id="ModalCenterTerminer" tabindex="-1" role="dialog" aria-labelledby="Enregistrer l'analyse" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header card_header_animation">
                        <h5 class="modal-title">{% trans %}Enregistrer l'analyse{% endtrans %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div>
                        <div class="row_flex modal_margin modal_label">
                            <p class="text_margin_right p_black">{% trans %}Nom :{% endtrans %}</p>
                            {{ form_widget(form.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Nom...'}} ) }}
                        </div>
                    </div>
                    <div class="group_button modal_margin">
                        <button type="button" class="button3_left" data-dismiss="modal">{% trans %}Annuler{% endtrans %}</button>
                        {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}

        <div class="group_button">
            <a class="button4_left" href="{{ path('adept_NFX35109_handling_without_assistance_constraints',  { 'id': idEvaluation }) }}">{% trans %}Revenir en arrière{% endtrans %}</a>
            <a class="button4_center" href="{{ path('adept_NFX35109_handling_without_assistance',  { 'id': idEvaluation }) }}">{% trans %}Ajouter une charge{% endtrans %}</a>
            <button id="button_Terminer" type="button" class="button4_center" data-toggle="modal" data-target="#ModalCenterTerminer">{% trans %}Terminer{% endtrans %}</button>
            {% if evaluation.evaluationED6161 != null %}
                <a class="button4_right" href="{{ path('adept_ED6161_resume',  { 'id': evaluation.evaluationED6161.evaluation.id }) }}">{% trans %}Retour à la hiérarchisation{% endtrans %}</a>
            {% else %}
                <a class="button4_right" href="{{ path('adept_menu') }}">{% trans %}Retour au menu principal{% endtrans %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/NFX35109/picture2.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <div class="row">
            <h1>{% trans %}Repérer{% endtrans %}</h1>
            <h1>></h1>
            <h1>{% trans %}Hiérarchiser{% endtrans %}</h1>
            <h1>></h1>
            <h1 class="mauve">{% trans %}Évaluer{% endtrans %}</h1>
        </div>
        <h1>{% trans %}Manutention Manuelle de charge - Importer une photo{% endtrans %}</h1>

        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.nom_fichier, 'Vous pouvez importer une photo ou vidéo de l\'activité à évaluer', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.nom_fichier, {'attr': {'class': 'button_import'}} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button_picture'}} ) }}
        </div>
        {% if fichier != null %}
            <h3>Liste des éléments :</h3>
            <a class="navbar-brand" href="{{ path('adept_NFX35109_picture_download', { 'id': fichier.id }) }}">
                {{ fichier.nomFichier }}
            </a>
            <a class="navbar-brand" href="{{ path('adept_NFX35109_delete_picture', { 'id': id, 'id2': fichier.id }) }}">
                <img src="/images/delete.png" alt="icon supprimer" id="icon_delete" class="icon_click">
            </a>
        {% endif %}
        {{ form_end(form) }}
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_NFX35109_activity',  { 'id': id }) }}">{% trans %}Retour{% endtrans %}</a>
            <a class="button3_right" href="{{ path('adept_NFX35109_operator',  { 'id': id }) }}">{% trans %}Poursuivre{% endtrans %}</a>
        </div>
    </div>
{% endblock %}

templates/NFX35109/results.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div>
        <div>
            <h1>Résumé</h1>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_NFX35109_constraints') }}" >Revenir en arrière</a>
            <a class="button3_right" href="{{ path('adept_menu') }}" >Retour au menu principal</a>
        </div>
    </div>
{% endblock %}