src/Entity/ChargeNFX.php
<?php

namespace App\Entity;

use App\Repository\ChargeNFXRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChargeNFXRepository::class)
 */
class ChargeNFX
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $poids_charge;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prise_hauteur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prise_profondeur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $depose_hauteur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $depose_profondeur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_initiale;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_initiale_reference;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_maintien;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $force_maintien_reference;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $distance_transport_charge;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $transport_charge;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_action;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_manutention_type;

    private $PT_lit;

    private $PT_transpalette;

    private $PT_chariot;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PT_distance;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PT_hauteur_poignee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PT_frequence;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_charge_identique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contraintes_execution;

    private $contrainte_poignees_inadaptees;

    private $contrainte_torsion_tronc;

    private $contrainte_profondeur_prise;

    private $contrainte_hors_zone_atteinte;

    private $contrainte_posture;

    private $contrainte_charge_instable;

    private $contrainte_visibilite_limitee;

    private $contrainte_roulettes_inadequates;

    private $contrainte_absence_frein;

    /**
     * @ORM\ManyToOne(targetEntity=EvaluationNFX::class, inversedBy="chargeNFXes")
     */
    private $evaluation_nfx;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coefficient_correction_1;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $coefficient_correction_2;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $masse_corrigee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $intitule_coefficient_correction_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $intitule_coefficient_correction_2;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoidsCharge(): ?float
    {
        return $this->poids_charge;
    }

    public function setPoidsCharge(float $poids_charge): self
    {
        $this->poids_charge = $poids_charge;

        return $this;
    }

    public function getPriseHauteur(): ?float
    {
        return $this->prise_hauteur;
    }

    public function setPriseHauteur(float $prise_hauteur): self
    {
        $this->prise_hauteur = $prise_hauteur;

        return $this;
    }

    public function getPriseProfondeur(): ?float
    {
        return $this->prise_profondeur;
    }

    public function setPriseProfondeur(float $prise_profondeur): self
    {
        $this->prise_profondeur = $prise_profondeur;

        return $this;
    }

    public function getDeposeHauteur(): ?float
    {
        return $this->depose_hauteur;
    }

    public function setDeposeHauteur(float $depose_hauteur): self
    {
        $this->depose_hauteur = $depose_hauteur;

        return $this;
    }

    public function getDeposeProfondeur(): ?float
    {
        return $this->depose_profondeur;
    }

    public function setDeposeProfondeur(float $depose_profondeur): self
    {
        $this->depose_profondeur = $depose_profondeur;

        return $this;
    }

    public function getForceInitiale(): ?float
    {
        return $this->force_initiale;
    }

    public function setForceInitiale(float $force_initiale): self
    {
        $this->force_initiale = $force_initiale;

        return $this;
    }

    public function getForceInitialeReference(): ?float
    {
        return $this->force_initiale_reference;
    }

    public function setForceInitialeReference(float $force_initiale_reference): self
    {
        $this->force_initiale_reference = $force_initiale_reference;

        return $this;
    }

    public function getForceMaintien(): ?float
    {
        return $this->force_maintien;
    }

    public function setForceMaintien(?float $force_maintien): self
    {
        $this->force_maintien = $force_maintien;

        return $this;
    }

    public function getForceMaintienReference(): ?float
    {
        return $this->force_maintien_reference;
    }

    public function setForceMaintienReference(?float $force_maintien_reference): self
    {
        $this->force_maintien_reference = $force_maintien_reference;

        return $this;
    }

    public function getDistanceTransportCharge(): ?float
    {
        return $this->distance_transport_charge;
    }

    public function setDistanceTransportCharge(float $distance_transport_charge): self
    {
        $this->distance_transport_charge = $distance_transport_charge;

        return $this;
    }

    public function getTransportCharge(): ?string
    {
        return $this->transport_charge;
    }

    public function setTransportCharge(string $transport_charge): self
    {
        $this->transport_charge = $transport_charge;

        return $this;
    }

    public function getPTAction(): ?string
    {
        return $this->PT_action;
    }

    public function setPTAction(?string $PT_action): self
    {
        $this->PT_action = $PT_action;

        return $this;
    }

    public function getPTManutentionType(): ?string
    {
        return $this->PT_manutention_type;
    }

    public function setPTManutentionType(?string $PT_manutention_type): self
    {
        $this->PT_manutention_type = $PT_manutention_type;

        return $this;
    }

    public function getPTLit(): ?bool
    {
        return $this->PT_lit;
    }

    public function setPTLit(bool $PT_lit): self
    {
        $this->PT_lit = $PT_lit;

        return $this;
    }

    public function getPTTranspalette(): ?bool
    {
        return $this->PT_transpalette;
    }

    public function setPTTranspalette(bool $PT_transpalette): self
    {
        $this->PT_transpalette = $PT_transpalette;

        return $this;
    }

    public function getPTchariot(): ?bool
    {
        return $this->PT_chariot;
    }

    public function setPTchariot(bool $PT_chariot): self
    {
        $this->PT_chariot = $PT_chariot;

        return $this;
    }

    public function getPTDistance(): ?float
    {
        return $this->PT_distance;
    }

    public function setPTDistance(?float $PT_distance): self
    {
        $this->PT_distance = $PT_distance;

        return $this;
    }

    public function getPTHauteurPoignee(): ?float
    {
        return $this->PT_hauteur_poignee;
    }

    public function setPTHauteurPoignee(?float $PT_hauteur_poignee): self
    {
        $this->PT_hauteur_poignee = $PT_hauteur_poignee;

        return $this;
    }

    public function getPTFrequence(): ?string
    {
        return $this->PT_frequence;
    }

    public function setPTFrequence(?string $PT_frequence): self
    {
        $this->PT_frequence = $PT_frequence;

        return $this;
    }

    public function getNombreChargeIdentique(): ?int
    {
        return $this->nombre_charge_identique;
    }

    public function setNombreChargeIdentique(int $nombre_charge_identique): self
    {
        $this->nombre_charge_identique = $nombre_charge_identique;

        return $this;
    }

    public function getContraintesExecution(): ?string
    {
        return $this->contraintes_execution;
    }

    public function setContraintesExecution(string $contraintes_execution): self
    {
        $this->contraintes_execution = $contraintes_execution;

        return $this;
    }

    public function getEvaluationNfx(): ?EvaluationNFX
    {
        return $this->evaluation_nfx;
    }

    public function setEvaluationNfx(?EvaluationNFX $evaluation_nfx): self
    {
        $this->evaluation_nfx = $evaluation_nfx;

        return $this;
    }

    public function getContraintePoigneesInadaptees(): ?bool
    {
        return $this->contrainte_poignees_inadaptees;
    }

    public function setContraintePoigneesInadaptees(bool $contrainte_poignees_inadaptees): self
    {
        $this->contrainte_poignees_inadaptees = $contrainte_poignees_inadaptees;

        return $this;
    }

    public function getContrainteTorsionTronc(): ?bool
    {
        return $this->contrainte_torsion_tronc;
    }

    public function setContrainteTorsionTronc(bool $contrainte_torsion_tronc): self
    {
        $this->contrainte_torsion_tronc = $contrainte_torsion_tronc;

        return $this;
    }

    public function getContrainteProfondeurPrise(): ?bool
    {
        return $this->contrainte_profondeur_prise;
    }

    public function setContrainteProfondeurPrise(bool $contrainte_profondeur_prise): self
    {
        $this->contrainte_profondeur_prise = $contrainte_profondeur_prise;

        return $this;
    }

src/Entity/Evaluation.php
<?php

namespace App\Entity;

use App\Repository\EvaluationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvaluationRepository::class)
 */
class Evaluation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_evaluation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_evaluation;

    /**
     * @ORM\ManyToOne(targetEntity=Evaluateur::class, inversedBy="evaluations")
     */
    private $evaluateur;

    /**
     * @ORM\ManyToOne(targetEntity=Situation::class, inversedBy="evaluations")
     */
    private $situation;

    /**
     * @ORM\OneToOne(targetEntity=EvaluationNFX::class, cascade={"persist", "remove"})
     */
    private $evaluation_nfx;

    /**
     * @ORM\ManyToOne(targetEntity=PosteDeTravail::class, inversedBy="evaluations")
     */
    private $posteDeTravail;

    /**
     * @ORM\ManyToOne(targetEntity=Secteur::class, inversedBy="evaluations")
     */
    private $secteur;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="evaluations")
     */
    private $site;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="evaluations")
     */
    private $entreprise;

    private $situation_nom;

    /**
     * @ORM\OneToMany(targetEntity=EvaluationED6161::class, mappedBy="evaluation")
     */
    private $evaluationED6161s;

    /**
     * @ORM\ManyToOne(targetEntity=EvaluationED6161::class, inversedBy="evaluations")
     */
    private $evaluationED6161;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $evaluation_interne;

    /**
     * @ORM\OneToMany(targetEntity=BilanEvaluation::class, mappedBy="evaluation")
     */
    private $bilanEvaluations;

    public function __construct()
    {
        $this->evaluationED6161s = new ArrayCollection();
        $this->bilanEvaluations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeEvaluation(): ?string
    {
        return $this->type_evaluation;
    }

    public function setTypeEvaluation(string $type_evaluation): self
    {
        $this->type_evaluation = $type_evaluation;

        return $this;
    }

    public function getDateEvaluation(): ?\DateTimeInterface
    {
        return $this->date_evaluation;
    }

    public function setDateEvaluation(\DateTimeInterface $date_evaluation): self
    {
        $this->date_evaluation = $date_evaluation;

        return $this;
    }

    public function getEvaluateur(): ?Evaluateur
    {
        return $this->evaluateur;
    }

    public function setEvaluateur(?Evaluateur $evaluateur): self
    {
        $this->evaluateur = $evaluateur;

        return $this;
    }

    public function getSituation(): ?Situation
    {
        return $this->situation;
    }

    public function setSituation(?Situation $situation): self
    {
        $this->situation = $situation;

        return $this;
    }

    public function getEvaluationNfx(): ?EvaluationNFX
    {
        return $this->evaluation_nfx;
    }

    public function setEvaluationNfx(?EvaluationNFX $evaluation_nfx): self
    {
        $this->evaluation_nfx = $evaluation_nfx;

        return $this;
    }

    public function getPosteDeTravail(): ?PosteDeTravail
    {
        return $this->posteDeTravail;
    }

    public function setPosteDeTravail(?PosteDeTravail $posteDeTravail): self
    {
        $this->posteDeTravail = $posteDeTravail;

        return $this;
    }

    public function getSecteur(): ?Secteur
    {
        return $this->secteur;
    }

    public function setSecteur(?Secteur $secteur): self
    {
        $this->secteur = $secteur;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getSituationNom(): ?string
    {
        return $this->situation_nom;
    }

    public function setSituationNom(?string $situation_nom): self
    {
        $this->situation_nom = $situation_nom;

        return $this;
    }

    /**
     * @return Collection|EvaluationED6161[]
     */
    public function getEvaluationED6161s(): Collection
    {
        return $this->evaluationED6161s;
    }

    public function addEvaluationED6161(EvaluationED6161 $evaluationED6161): self
    {
        if (!$this->evaluationED6161s->contains($evaluationED6161)) {
            $this->evaluationED6161s[] = $evaluationED6161;
            $evaluationED6161->setEvaluation($this);
        }

        return $this;
    }

    public function removeEvaluationED6161(EvaluationED6161 $evaluationED6161): self
    {
        if ($this->evaluationED6161s->removeElement($evaluationED6161)) {
            // set the owning side to null (unless already changed)
            if ($evaluationED6161->getEvaluation() === $this) {
                $evaluationED6161->setEvaluation(null);
            }
        }

        return $this;
    }

    public function getEvaluationED6161(): ?EvaluationED6161
    {
        return $this->evaluationED6161;
    }

    public function setEvaluationED6161(?EvaluationED6161 $evaluationED6161): self
    {
        $this->evaluationED6161 = $evaluationED6161;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEvaluationInterne(): ?bool
    {
        return $this->evaluation_interne;
    }

    public function setEvaluationInterne(bool $evaluation_interne): self
    {
        $this->evaluation_interne = $evaluation_interne;

        return $this;
    }

    /**
     * @return Collection|BilanEvaluation[]
     */
    public function getBilanEvaluations(): Collection
    {
        return $this->bilanEvaluations;
    }

    public function addBilanEvaluation(BilanEvaluation $bilanEvaluation): self
    {
        if (!$this->bilanEvaluations->contains($bilanEvaluation)) {
            $this->bilanEvaluations[] = $bilanEvaluation;
            $bilanEvaluation->setEvaluation($this);
        }

        return $this;
    }

    public function removeBilanEvaluation(BilanEvaluation $bilanEvaluation): self
    {
        if ($this->bilanEvaluations->removeElement($bilanEvaluation)) {
            // set the owning side to null (unless already changed)
            if ($bilanEvaluation->getEvaluation() === $this) {
                $bilanEvaluation->setEvaluation(null);
            }
        }

        return $this;
    }
}

templates/general/analyseChoice.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_900">
        <div class="center">
            <p id="p_button">{% trans %}Laissez-vous guider{% endtrans %} :</p>
            <a class="button" id="button_p" href="{{ path('adept_tool_guide') }}" >Je me laisse guider</a>
        </div>
        <div class="center">
            <p id="p_button">{% trans %}Ou choisissez votre outil de cotation{% endtrans %} :</p>
            <a class="button" id="button_p" href="{{ path('adept_ergonomics_tools_list') }}" >{% trans %}Choisir l'outil de cotation{% endtrans %}</a>
        </div>
        <div>
            <a class="button" href="{{ path('adept_menu') }}" >{% trans %}Retourner au menu principal{% endtrans %}</a>
        </div>
    </div>
{% endblock %}

templates/general/balanceSheetPoste.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <h1>{% trans %}Bilan d'entreprise{% endtrans %} : {{ entreprise.nom }}</h1>
        <div class="container">
            {% set sites = [] %}
            {% set secteurs = [] %}
            {% set postes = [] %}
            {% for site in form.sites %}
                {% if site.entreprise.id == entreprise.id %}
                    {% set sites = sites|merge([site]) %}
                {% endif %}
            {% endfor %}

            <div class="top_container row" id="site">
                {{ form_label(form.sites, 'Sélectionner le site :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.sites, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un site existant ...'} }) }}
                {{ form_errors(form.sites) }}
            </div>
            <div class="top_container row" id="secteur">
                {{ form_label(form.secteurs, 'Sélectionner le secteur :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.secteurs, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un secteur existant ...'} }) }}
                {{ form_errors(form.secteurs) }}
            </div>
            <div class="top_container row" id="posteDeTravail">
                {{ form_label(form.posteDeTravails, 'Sélectionner le poste :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.posteDeTravails, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un poste de travail existant ...'} }) }}
                {{ form_errors(form.posteDeTravails) }}
            </div>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_company_balance_sheet') }}" >{% trans %}Retourner au menu principal{% endtrans %}</a>
            {{ form_label(form.valider, 'Continuer', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
        </div>
    </div>
{% endblock %}

templates/general/balanceSheetSecteur.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <h1>{% trans %}Bilan d'entreprise{% endtrans %} : {{ entreprise.nom }}</h1>
        <div class="container">
            {% set sites = [] %}
            {% set secteurs = [] %}
            {% for site in form.sites %}
                {% if site.entreprise.id == entreprise.id %}
                    {% set sites = sites|merge([site]) %}
                {% endif %}
            {% endfor %}
            
            <div class="top_container row" id="site">
                {{ form_label(form.sites, 'Sélectionner le site :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.sites, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un site existant ...'} }) }}
                {{ form_errors(form.sites) }}
            </div>
            <div class="top_container row" id="secteur">
                {{ form_label(form.secteurs, 'Sélectionner le secteur :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.secteurs, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un secteur existant ...'} }) }}
                {{ form_errors(form.secteurs) }}
            </div>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_company_balance_sheet') }}" >{% trans %}Retourner au menu principal{% endtrans %}</a>
            {{ form_label(form.valider, 'Continuer', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
        </div>
    </div>
{% endblock %}

templates/general/balanceSheetSite.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <h1>{% trans %}Bilan d'entreprise{% endtrans %} : {{ entreprise.nom }}</h1>
        <div class="container">
            {% set sites = [] %}
            {% for site in form.sites %}
                {% if site.entreprise.id == entreprise.id %}
                    {% set sites = sites|merge([site]) %}
                {% endif %}
            {% endfor %}

            <!--<label for="pet-select" class="p_white">Choisir un site:</label>
            <select name="pets" id="pet-select">
                <option value="">--Sélectionner un site--</option>
                {% for site in sites %}
                    <option value={{ site.id }}>{{ site.nom }}</option>
                {% endfor %}
            </select>-->
            <div class="top_container row" id="site">
                {{ form_label(form.sites, 'Sélectionner le site :', {'label_attr': {'class': 'p'}} ) }}
                {{ form_widget(form.sites, {'attr': {'class': 'form-control', 'placeholder': 'Sélection d\'un site existant ...'} }) }}
                {{ form_errors(form.sites) }}
            </div>
        </div>
        <div class="group_button">
            <a class="button3_left" href="{{ path('adept_company_balance_sheet') }}" >{% trans %}Retourner au menu principal{% endtrans %}</a>
            {{ form_label(form.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3_center'}} ) }}
            {{ form_label(form.ajouter, 'Ajouterj', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.ajouter, {'attr': {'class': 'button3_right'}} ) }}
        </div>
    </div>
{% endblock %}

templates/general/search.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="fixe_largeur_90">
        <h1 class="h_margin_bottom">{% trans %}Rechercher une évaluation{% endtrans %}</h1>
        {{ form_start(form) }}

        <div class="margin_bottom row_flex col-xl-6 col-lg-6 col-md-6 col-sm-6">
            {{ form_widget(form.nom, {'attr': {'class': 'form_control_60', 'placeholder': 'Nom...'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3_right'}} ) }}
        </div>

        <table class="table table-striped table-hover table-light">
            <thead>
                <tr>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Ordre{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Évaluateur{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Type évaluation{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Intitulé{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Date{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Voir{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Télécharger{% endtrans %}</th>
                    <th scope="col" class="mauve_cell" style="text-align:center">{% trans %}Supprimer{% endtrans %}</th>
                </tr>
            </thead>
            <tbody>
                {% for evaluation in listeEvaluations %}
                <tr>
                    <th scope="row" style="text-align:center">{{ loop.index }}</th>
                    <td style="text-align:center">{{ evaluation.evaluateur.nom }} {{ evaluation.evaluateur.prenom }}</td>
                    <td style="text-align:center">{{ evaluation.typeEvaluation }}</td>
                    <td style="text-align:center">{{ evaluation.Nom }}</td>
                    <td style="text-align:center">{{ evaluation.dateEvaluation |date("m/d/Y") }}</td>
                    {% if evaluation.typeEvaluation == "ED6161" %}
                        <td style="text-align:center">
                            <a href="{{ path('adept_ED6161_resume', {'id':evaluation.id} ) }}">
                                <img src="/images/edit.png" alt="icon editer" id="icon_edit" class="icon_click">
                            </a>
                        </td>
                    {% elseif evaluation.typeEvaluation == "NF X35-109" %}
                        {% if evaluation.evaluationNfx.typeManutention == "Sans aide à la manutention" %}
                            <td style="text-align:center">
                                <a href="{{ path('adept_NFX35109_handling_without_assistance_resume', {'id':evaluation.id} ) }}">
                                    <img src="/images/edit.png" alt="icon editer" id="icon_edit" class="icon_click">
                                </a>
                            </td>
                        {% elseif evaluation.evaluationNfx.typeManutention == "Avec aide à la manutention" %}
                            <td style="text-align:center">
                                <a href="{{ path('adept_NFX35109_handling_with_assistance_resume', {'id':evaluation.id} ) }}">
                                    <img src="/images/edit.png" alt="icon editer" id="icon_edit" class="icon_click">
                                </a>
                            </td>
                        {% else %}
                            <td style="text-align:center">
                                <a href="{{ path('adept_tool_NFX35109', {'id':evaluation.id} ) }}">
                                    <img src="/images/edit.png" alt="icon editer" id="icon_edit" class="icon_click">
                                </a>
                            </td>
                        {% endif %}
                    {% elseif evaluation.typeEvaluation == "Non défini" %}
                        <td style="text-align:center">
                            <a href="{{ path('adept_tool_guide', {'id':evaluation.id} ) }}">
                                <img src="/images/edit.png" alt="icon editer" id="icon_edit" class="icon_click">
                            </a>
                        </td>
                    {% endif %}
                    <td style="text-align:center">
                        <a href="{{ path('adept_download_evaluation', {'id': evaluation.id} ) }}">
                            <img src="/images/download_pdf.png" alt="icon download" id="icon_download" class="icon_click">
                        </a>
                    </td>
                    <td style="text-align:center">
                        <a href="{{ path('adept_delete_evaluation', {'id': evaluation.id} ) }}">
                            <img src="/images/delete.png" alt="icon supprimer" id="icon_delete" class="icon_click">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {{ form_end(form) }}

        <div>
            <a class="button" href="{{ path('adept_menu') }}">{% trans %}Retourner au menu principal{% endtrans %}</a>
        </div>
    </div>
{% endblock %}